site_name: H2O Nitro
site_description: The quickest way to build web apps in Python
site_author: Prithvi Prabhu
repo_name: h2oai/nitro
repo_url: https://github.com/h2oai/nitro
copyright: "Copyright &copy; 2022 <a href='https://h2o.ai'>H2O.ai, Inc</a>. Licensed under <a href='https://opensource.org/licenses/BSD-3-Clause'>BSD 3-Clause</a>."
theme:
  name: material
  icon:
    logo: material/rocket-launch-outline
  features:
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.top
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/h2oai/nitro
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/h2o-nitro/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/h2o_nitro
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: 'index.md'
  # Generated
  - Guide:
    - 'basics.md'
    - 'markdown.md'
    - 'layout.md'
    - 'forms.md'
    - 'textbox.md'
    - 'spinbox.md'
    - 'pickers.md'
    - 'options.md'
    - 'buttons.md'
    - 'radio-buttons.md'
    - 'dropdown.md'
    - 'dropdown-list.md'
    - 'checklist.md'
    - 'slider.md'
    - 'range-slider.md'
    - 'time-picker.md'
    - 'date-picker.md'
    - 'calendar.md'
    - 'week-picker.md'
    - 'month-picker.md'
    - 'tag-picker.md'
    - 'color-picker.md'
    - 'color-palette.md'
    - 'rating.md'
