site_name: H2O Nitro
site_description: The simplest way to build web apps in Python
site_author: Prithvi Prabhu
repo_name: h2oai/nitro
repo_url: https://github.com/h2oai/nitro
copyright: "Copyright &copy; 2022 <a href='https://h2o.ai'>H2O.ai, Inc</a>. Licensed under <a href='https://www.apache.org/licenses/LICENSE-2.0'>Apache-2.0</a>."
theme:
  name: material
  logo: assets/nitro.svg
  features:
    - header.autohide
    - navigation.sections
    - navigation.indexes
    - navigation.top
  font:
    text: Roboto Slab
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/h2oai/nitro
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/h2o-nitro/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/h2o_nitro
markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
nav:
  - Introduction: 'index.md'
  - 'install.md'
  # Begin generated
  - Guide:
    - 'basics.md'
    - 'markdown.md'
    - 'styling.md'
    - 'images.md'
    - 'layout.md'
    - 'forms.md'
    - 'popups.md'
    - 'textbox.md'
    - 'spinbox.md'
    - 'checkbox.md'
    - 'toggle.md'
    - 'pickers.md'
    - 'options.md'
    - 'buttons.md'
    - 'radio-buttons.md'
    - 'dropdown.md'
    - 'dropdown-list.md'
    - 'checklist.md'
    - 'table.md'
    - 'slider.md'
    - 'range-slider.md'
    - 'time-picker.md'
    - 'date-picker.md'
    - 'calendar.md'
    - 'week-picker.md'
    - 'month-picker.md'
    - 'tag-picker.md'
    - 'color-picker.md'
    - 'color-palette.md'
    - 'rating.md'
    - 'file-upload.md'
    - 'separator.md'
    - 'theming.md'
    - 'advanced-layout.md'
    # End generated
  - Meta:
      - 'change-log.md'